files:
  - source: /en/**/*.md
    translation: /%two_letters_code%/**/%original_file_name%
    languages_mapping:
      two_letters_code:
        zh-CN: zh-CN
        zh-TW: zh-TW
        pt-PT: pt
        pt-BR: pt-BR
